name: elgato_keylight_api
description: This package provides a wrapper around Elgato Keylight's API
version: 1.0.0
homepage: https://github.com/g123k/dart_elgato_keylights_api

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: any
  lints: any